In [2]:
import pandas as pd
import requests

In [24]:
response = requests.get('https://api.fiscaldata.treasury.gov/services/api/fiscal_service/v1/accounting/dts/deposits_withdrawals_operating_cash')
data = response.json()['data']


df = pd.DataFrame(data)

In [23]:
# Define the base URL and endpoint
url = 'https://api.fiscaldata.treasury.gov/services/api/fiscal_service/v1/accounting/dts/deposits_withdrawals_operating_cash'

# Initialize parameters for pagination and sorting
limit = 100  # Number of rows to fetch per request (assuming the API limits you to 100)
offset = 0   # Start from the first row
total_rows = 1000  # Target number of rows
all_data = []

# Loop to request data in batches of 'limit' until we get the top 1000 rows
while len(all_data) < total_rows:
    # Define the parameters for the API request (including sorting and pagination)
    params = {
        'limit': limit,          # Fetch 100 rows at a time
        'offset': offset,        # Use the offset to get the next set of rows
        'sort': 'date',          # Sort by date (most recent first)
        'order': 'desc'          # Order descending (newest first)
        # Add any other necessary parameters here (like filters)
    }

    # Make the API request
    response = requests.get(url, params=params)
    data = response.json()
    
    # Extract the relevant part of the data
    rows = data.get('results', [])  # Adjust according to the API structure

    # Append the rows to your data list
    all_data.extend(rows)

    # Increment the offset to get the next batch of data
    offset += limit

    # Break if there are no more rows (in case there are fewer than 1000 rows available)
    if not rows:
        break

# Convert the full dataset into a pandas DataFrame
df = pd.DataFrame(all_data[:total_rows])  # Get exactly 1000 rows (in case more were fetched)

# Display the DataFrame
print(df.head())

,record_date,account_type,transaction_type,transaction_catg,transaction_catg_desc,transaction_today_amt,transaction_mtd_amt,transaction_fytd_amt,table_nbr,table_nm,src_line_nbr,record_fiscal_year,record_fiscal_quarter,record_calendar_year,record_calendar_quarter,record_calendar_month,record_calendar_day
0,2005-10-03,Federal Reserve Account,Deposits,Agriculture Loan Repayments (misc),null,62,62,62,II,Deposits and Withdrawals of Operating Cash,1,2006,1,2005,4,10,03
1,2005-10-03,Federal Reserve Account,Deposits,Commodity Credit Corporation programs,null,61,61,61,II,Deposits and Withdrawals of Operating Cash,2,2006,1,2005,4,10,03
2,2005-10-03,Federal Reserve Account,Deposits,Customs and Certain Excise Taxes,null,127,127,127,II,Deposits and Withdrawals of Operating Cash,3,2006,1,2005,4,10,03
3,2005-10-03,Federal Reserve Account,Deposits,Deposits by States,Supplemental Security Income,2,2,2,II,Deposits and Withdrawals of Operating Cash,4,2006,1,2005,4,10,03
4,2005-10-03,Federal Reserve Account,Deposits,Deposits by States,Unemployment,12,12,12,II,Deposits and Withdrawals of Operating Cash,5,2006,1,2005,4,10,03
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2005-10-04,Federal Reserve Account,Withdrawals,Medicaid,null,591,1565,1565,II,Deposits and Withdrawals of Operating Cash,42,2006,1,2005,4,10,04
96,2005-10-04,Federal Reserve Account,Withdrawals,Medicare,null,1287,2238,2238,II,Deposits and Withdrawals of Operating Cash,43,2006,1,2005,4,10,04
97,2005-10-04,Federal Reserve Account,Withdrawals,NASA programs,null,5,5,5,II,Deposits and Withdrawals of Operating Cash,44,2006,1,2005,4,10,04
98,2005-10-04,Federal Reserve Account,Withdrawals,Postal Service Money Orders and Other,null,174,402,402,II,Deposits and Withdrawals of Operating Cash,45,2006,1,2005,4,10,04
99,2005-10-04,Federal Reserve Account,Withdrawals,Public Debt Cash Redemp. (Table III-B),null,801,4051,4051,II,Deposits and Withdrawals of Operating Cash,46,2006,1,2005,4,10,04